# Enough disk for the system, the Windows compatibility layer and a game or
# two; enough memory for a GNOME desktop.
---
showSupportUrl:         true
showKnownIssuesUrl:     true
showReleaseNotesUrl:    false
requirements:
    requiredStorage:    25
    requiredRam:        2.0
    internetCheckUrl:   https://github.com
    check:
        - storage
        - ram
        - power
        - internet
        - root
    required:
        - root
        - storage
        - ram
geoip:
    style:  "none"
